[Interface]
Address = 10.60.0.1/24
ListenPort = 51820
PrivateKey = CHANGE_ME_SERVER_PRIVATE_KEY
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT

[Peer]
PublicKey = CHANGE_ME_CLIENT_PUBLIC_KEY
AllowedIPs = 10.60.0.10/32
